---

name: Docker Build + Run Test

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:

  b2bua-build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: b2bua:test
          platforms: linux/amd64

      - name: Run Docker image
        run: |
          set -e
          timeout 30s docker run --rm b2bua:test || [ "$?" -eq 124 ]
